name: Issue or PR Comment Workflow

on:
  issue_comment:
    types: [created] 

jobs:
  show-comment-info:
    runs-on: ubuntu-latest
    steps:
      - name: Show event info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Comment Author: ${{ github.event.comment.user.login }}"
          echo "Comment Body: ${{ github.event.comment.body }}"
          echo "Comment URL: ${{ github.event.comment.html_url }}"
          echo "Number: ${{ github.event.issue.number }}"
